GetA-BEER/GetABeer

fe/src/pages/atoms/examples.tsx
개발환경 추가 세팅
- Set Recoil 
- Set Axios
=> GB-22:FE초기 개발환경 세팅

be/build.gradle
-기존 세팅이 구버전이라 최신버전으로 수정했습니다.
-이외에는 변경사항 전혀 없습니다!
=> GB-16 fix : Query DSL 버전 변경

be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/chatting/entity/ChatMessage.java, be/src/main/java/be/domain/chatting/entity/ChatRoom.java, be/src/main/java/be/domain/comment/entity/BeerComment.java, be/src/main/java/be/domain/pairing/entity/Pairing.java, be/src/main/java/be/domain/pairing/entity/PairingCategory.java, be/src/main/java/be/domain/pairing/entity/PairingImage.java, be/src/main/java/be/domain/recomment/entity/BeerRecomment.java, be/src/main/java/be/domain/recomment/entity/PairingRecomment.java
- 댓글 관련 엔티티 구현
- BeerComment
- Pairing
- BeerRecomment
- PairingRecomment
- PairingCategory
- 채팅 관련 엔티티 구현 (이후 구현 방식에 따라 사라질 수도 있음)
- ChatRoom
- ChatMessage
=> GB-23 feat: 댓글 관련 및 채팅 관련 엔티티 구현 및 연관관계 매핑

be/src/main/java/be/domain/user/controller/UserController.java, be/src/main/java/be/domain/user/dto/UserDto.java, be/src/main/java/be/domain/user/entity/User.java, be/src/main/java/be/domain/user/entity/UserBeerTag.java, be/src/main/java/be/domain/user/mapper/UserMapper.java, be/src/main/java/be/domain/user/repository/UserRepository.java, be/src/main/java/be/domain/user/service/UserService.java
=> GB-23 feat: User Domain 개발 준비단계 구현

be/src/main/java/be/domain/comment/controller/BeerCommentController.java, be/src/main/java/be/domain/comment/dto/BeerCommentDto.java, be/src/main/java/be/domain/comment/entity/BeerComment.java, be/src/main/java/be/domain/comment/mapper/BeerCommentMapper.java, be/src/main/java/be/domain/comment/service/BeerCommentService.java
- 맥주 코멘트 등록, 수정, 삭제 구현
- 특정 맥주 코멘트 조회 구현
=> GB-27 feat: Implement BeerComment CUD

be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/beer/entity/MonthlyBeer.java, be/src/main/java/be/domain/beer/entity/MonthlyBeerBeerCategory.java, be/src/main/java/be/domain/beer/entity/MonthlyBeerBeerTag.java, be/src/main/java/be/domain/beercategory/entity/BeerCategory.java, be/src/main/java/be/domain/beertag/entity/BeerTag.java, be/src/main/java/be/domain/beerwishlist/entity/BeerWishlist.java, be/src/main/java/be/domain/crawler/TestCrawler.java, be/src/main/java/be/global/init/Init.java
- User 엔티티와 매핑 완료했습니다.
- 테스트시 발견된 오류를 수정하고 문서를 고치고 있습니다.
- 유저-위시리스트를 제외한 연관관계 메서드 완성했습니다.
=> GB-31 fix: Beer Domain Error Handling

be/.gitignore, be/build.gradle, be/src/main/java/be/domain/beer/controller/BeerController.java, be/src/main/java/be/domain/beer/dto/BeerDto.java, be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/beer/entity/BeerDetailsBasic.java, be/src/main/java/be/domain/beer/entity/BeerDetailsBestRating.java, be/src/main/java/be/domain/beer/entity/BeerDetailsCounts.java, be/src/main/java/be/domain/beer/entity/BeerDetailsStars.java, be/src/main/java/be/domain/beer/entity/BeerDetailsTopTags.java, be/src/main/java/be/domain/beer/mapper/BeerMapper.java, be/src/main/java/be/domain/beer/repository/BeerQueryRepository.java, be/src/main/java/be/domain/beercategory/entity/BeerCategoryType.java, be/src/main/java/be/domain/beertag/repository/BeerTagQueryRepository.java, be/src/main/java/be/domain/beertag/repository/BeerTagRepository.java, be/src/main/java/be/domain/crawler/SeleniumConstant.java, be/src/main/java/be/domain/crawler/SeleniumStarter.java, be/src/main/java/be/domain/search/controller/SearchController.java, be/src/main/java/be/domain/search/controller/VisionController.java, be/src/main/java/be/domain/search/service/SearchService.java, be/src/main/java/be/global/config/PasswordEncoderConfig.java, be/src/main/java/be/global/init/InitConstant.java, be/src/main/java/be/global/security/auth/filter/JwtAuthenticationFilter.java, be/src/main/java/be/global/security/auth/jwt/JwtTokenizer.java, be/src/main/resources/application.yml
- 크롤링 로직 예외처리 추가로 거의 완성했습니다.
- 이미지 인식 테스트를 위해 이것저것 추가하다가 일이 좀 커졌는데 너무 커지기 전에 멈췄습니다.
=> GB-33 feat: 데이터 수집 준비

be/src/main/java/be/domain/pairing/controller/PairingController.java, be/src/main/java/be/domain/pairing/controller/PairingController2.java, be/src/main/java/be/domain/pairing/dto/PairingDto.java, be/src/main/java/be/domain/pairing/dto/PairingImageDto.java, be/src/main/java/be/domain/pairing/entity/Pairing.java, be/src/main/java/be/domain/pairing/entity/Pairing2.java, be/src/main/java/be/domain/pairing/entity/PairingImage.java, be/src/main/java/be/domain/pairing/entity/PairingImage2.java, be/src/main/java/be/domain/pairing/mapper/PairingMapper.java, be/src/main/java/be/domain/pairing/mapper/PairingMapper2.java, be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java, be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java, be/src/main/java/be/domain/pairing/repository/PairingImageRepository2.java, be/src/main/java/be/domain/pairing/repository/PairingRepository2.java, be/src/main/java/be/domain/pairing/service/PairingService.java, be/src/main/java/be/domain/pairing/service/PairingService2.java, be/src/main/java/be/domain/rating/controller/RatingController.java, be/src/main/java/be/domain/rating/dto/RatingDto.java, be/src/main/java/be/domain/rating/dto/RatingTagDto.java, be/src/main/java/be/domain/rating/entity/Rating.java, be/src/main/java/be/domain/rating/entity/RatingTag.java, be/src/main/java/be/domain/rating/mapper/RatingMapper.java, be/src/main/java/be/domain/rating/repository/RatingTagRepository.java, be/src/main/java/be/domain/rating/service/RatingService.java, be/src/main/java/be/global/exception/ExceptionCode.java
- 평가 태그 구현
- 페어링 수정 구현
- 일반 : 일대일
- v2 / 2 : 다대일
- 다대일은 다른 방식으로 수정 고민 중 입니다.
=> GB-27 feat: Implement RatingTag And Implement Pairing PatchMapping

fe/components/beerPage/PairingTitle.tsx, fe/pages/beer/index.tsx
- paring -> pairing 오타 수정 합니다 ,,, 제송합니다 ㅠㅠ
=> GB-37 fix: 오타수정

fe/components/button/CloseBtn.tsx, fe/components/button/SubmitBtn.tsx, fe/components/inputs/Input.tsx, fe/pages/index.tsx
=> GB-38 style: 버튼 컴포넌트 수정, 인풋 컴포넌트 제작

be/build.gradle, be/src/main/java/be/global/config/S3Config.java, be/src/main/java/be/global/exception/ExceptionCode.java, be/src/main/java/be/global/image/ImageUploadController.java, be/src/main/java/be/global/image/S3UploadService.java, be/src/main/java/be/global/image/S3UploadServiceImpl.java, be/src/main/resources/application.yml
- S3 이미지 업로드 구현
- 리사이징 메서드 추가
- 현재 리사이징에서 BufferedImage로 변환이 되지 않는 문제 발생 (해결중)
=> GB-41 feat: Implement Upload Image To S3

be/src/main/java/be/domain/comment/controller/RatingCommentController.java, be/src/main/java/be/domain/comment/dto/RatingCommentDto.java, be/src/main/java/be/domain/comment/entity/RatingComment.java, be/src/main/java/be/domain/comment/mapper/RatingCommentMapper.java, be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepository.java, be/src/main/java/be/domain/comment/repository/RatingCommentCustomRepositoryImpl.java, be/src/main/java/be/domain/comment/service/RatingCommentService.java, be/src/main/java/be/global/aop/GetABeerAop.java, be/src/main/java/be/global/exception/ExceptionCode.java
- 맥주 평가 댓글 CRUD 구현
- 무한 댓글 조회로 협의
=> GB-44 feat: Implement RatingComment

be/src/main/java/be/domain/pairing/controller/PairingController.java, be/src/main/java/be/domain/rating/controller/RatingController.java
=> GB-60 fix: URI api 추가

be/src/main/java/be/domain/beer/controller/BeerController.java, be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/beer/entity/BeerBeerCategory.java, be/src/main/java/be/domain/beer/entity/BeerBeerTag.java, be/src/main/java/be/domain/beer/entity/BeerDetailsBestRating.java, be/src/main/java/be/domain/beer/entity/BeerDetailsCounts.java, be/src/main/java/be/domain/beer/entity/BeerDetailsStars.java, be/src/main/java/be/domain/beer/entity/BeerDetailsStatistics.java, be/src/main/java/be/domain/beer/entity/BeerDetailsTopTags.java, be/src/main/java/be/domain/beer/entity/MonthlyBeer.java, be/src/main/java/be/domain/beercategory/entity/BeerCategory.java, be/src/main/java/be/domain/beertag/entity/BeerTag.java, be/src/main/java/be/global/BaseTimeEntity.java, be/src/main/java/be/global/aop/GetABeerAop.java, be/src/main/java/be/global/aop/Pointcuts.java, be/src/main/java/be/global/scheduler/BeerScheduler.java, be/src/main/java/be/global/statistics/entity/BeerStatistics.java, be/src/main/java/be/global/statistics/repository/BeerStatisticsJdbcRepository.java, be/src/main/java/be/global/statistics/repository/BeerStatisticsQueryRepository.java, be/src/main/java/be/global/statistics/repository/BeerStatisticsRepository.java, be/src/main/java/be/global/statistics/service/StatisticsService.java
- AOP 에러 핸들링 및 테스트 완료했습니다.
- 통계자료 작성을 위한 테이블 작업중입니다.
- JDBC Bulk Insert 구현 및 로직 작성했습니다.
- 매일 오전 00시 10분에 맥주 통계 작성 후 리셋되도록 설정했습니다.
=> GB-50 feat: 통계 및 크롤링 준비

fe/atoms/currentBeer.tsx, fe/components/beerPage/BeerDetailCard.tsx, fe/components/beerPage/StarScore.tsx, fe/components/pairing/DetailCard.tsx, fe/components/pairing/PairingCard.tsx, fe/components/pairing/PairingImageCarousel.tsx, fe/components/smallCards/SmallCard.tsx, fe/components/smallCards/SmallPairingCard.tsx, fe/components/smallCards/SmallTag.tsx, fe/pages/beer/[id].tsx, fe/pages/pairing/[id].tsx, fe/pages/pairing/index.tsx, fe/pages/postpairing/index.tsx
=> GB-56 chore: 디테일 카드 생성

fe/components/pairing/PairingImageCarousel.tsx
=> GB-56 chore: 버셀 확인

be/src/main/java/be/domain/comment/service/PairingCommentService.java, be/src/main/java/be/domain/like/controller/PairingLikeController.java, be/src/main/java/be/domain/like/controller/RatingLikeController.java, be/src/main/java/be/domain/like/entity/LikeStatus.java, be/src/main/java/be/domain/like/entity/PairingLike.java, be/src/main/java/be/domain/like/entity/RatingLike.java, be/src/main/java/be/domain/like/repository/PairingLikeCustomRepository.java, be/src/main/java/be/domain/like/repository/PairingLikeCustomRepositoryImpl.java, be/src/main/java/be/domain/like/repository/PairingLikeRepository.java, be/src/main/java/be/domain/like/repository/RatingLikeCustomRepository.java, be/src/main/java/be/domain/like/repository/RatingLikeCustomRepositoryImpl.java, be/src/main/java/be/domain/like/repository/RatingLikeRepository.java, be/src/main/java/be/domain/like/service/PairingLikeService.java, be/src/main/java/be/domain/like/service/RatingLikeService.java, be/src/main/java/be/domain/pairing/controller/PairingController.java, be/src/main/java/be/domain/pairing/dto/PairingResponseDto.java, be/src/main/java/be/domain/pairing/entity/Pairing.java, be/src/main/java/be/domain/pairing/repository/PairingCustomRepository.java, be/src/main/java/be/domain/pairing/repository/PairingCustomRepositoryImpl.java, be/src/main/java/be/domain/pairing/service/PairingService.java, be/src/main/java/be/domain/rating/dto/RatingResponseDto.java, be/src/main/java/be/domain/rating/entity/Rating.java, be/src/main/java/be/domain/rating/service/RatingService.java, be/src/main/java/be/domain/user/entity/User.java, be/src/main/java/be/global/exception/ExceptionCode.java, be/src/main/java/be/global/image/PairingImageHandler.java
- 추천 구현
- 전체 회의 이후 추천 요청 나눌 시 수정 예정
- 로그인 유저 페어링, 평가 추천 여부에 따른 응답값 추가
=> GB-61 feat: 추천 구현

be/build.gradle, be/src/main/java/be/GetABeerApplication.java, be/src/main/java/be/domain/beer/controller/BeerController.java, be/src/main/java/be/domain/beer/dto/BeerDto.java, be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/beer/entity/WeeklyBeer.java, be/src/main/java/be/domain/beer/mapper/BeerMapper.java, be/src/main/java/be/domain/beer/repository/BeerQueryRepository.java, be/src/main/java/be/domain/beer/repository/BeerRepository.java, be/src/main/java/be/domain/beer/repository/WeeklyBeerQueryRepository.java, be/src/main/java/be/domain/beer/repository/WeeklyBeerRepository.java, be/src/main/java/be/domain/beer/service/BeerService.java, be/src/main/java/be/domain/beer/service/BeerServiceImpl.java, be/src/main/java/be/domain/beercategory/entity/BeerCategoryType.java, be/src/main/java/be/domain/elasticsearch/entity/AnalysisBeer.java, be/src/main/java/be/domain/elasticsearch/repository/BeerSearchRepository.java, be/src/main/java/be/domain/elasticsearch/service/EsAutoCompleteService.java, be/src/main/java/be/domain/search/controller/VisionController.java, be/src/main/java/be/domain/search/service/VisionService.java, be/src/main/java/be/global/config/CacheConstant.java, be/src/main/java/be/global/config/ElasticsearchConfig.java, be/src/main/java/be/global/config/RedisConfig.java, be/src/main/java/be/global/scheduler/GetABeerScheduler.java, be/src/main/java/be/global/statistics/entity/BeerCategoryStatistics.java, be/src/main/java/be/global/statistics/repository/BeerCategoryStatisticsQueryRepository.java, be/src/main/resources/application.yml
- 전체회의에 안건으로 나왔던 것들 구현했습니다.
- 매주 목요일 00시 05분에 인기 많은 맥주가 갱신됩니다.
- 맥주에 대한 각종 쿼리들 완성했습니다.
- ES설치 없이 돌아가는 것도 확인했습니다.
=> GB-72 feat: 전체회의 안건 구현

be/src/main/java/be/domain/pairing/controller/PairingController.java, be/src/main/java/be/domain/pairing/dto/PairingRequestDto.java, be/src/main/java/be/domain/pairing/entity/Pairing.java, be/src/main/java/be/domain/pairing/entity/PairingCategory.java, be/src/main/java/be/domain/pairing/mapper/PairingMapper.java, be/src/main/java/be/domain/pairing/service/PairingService.java, be/src/main/java/be/domain/rating/entity/RatingTag.java, be/src/main/java/be/domain/rating/mapper/RatingTagMapper.java, be/src/main/java/be/domain/rating/repository/RatingCustomRepository.java, be/src/main/java/be/domain/rating/repository/RatingCustomRepositoryImpl.java, be/src/main/java/be/domain/rating/service/RatingService.java, be/src/main/java/be/global/exception/ExceptionCode.java
- 페어링 카테고리 부분 수정
- 페어링 요청 파트 부분 수정
- 카테고리 수정하면서 매퍼 수정
- 페어링 매퍼 수정하면서 디폴드 저장값도 수정
- 평가 유저가 다른 비어에 중복 평가 안되는 이슈 수정
- 평가 무향 요청 판별 메서드 수정
=> GB-61 fix: Rating And Pairing

be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/beer/entity/BeerBeerCategory.java, be/src/main/java/be/domain/beer/entity/BeerBeerTag.java, be/src/main/java/be/domain/beer/mapper/BeerMapper.java, be/src/main/java/be/domain/beer/repository/BeerQueryRepository.java, be/src/main/java/be/domain/beerwishlist/entity/BeerWishlist.java, be/src/main/java/be/domain/gcp/Controller/ProductController.java, be/src/main/java/be/domain/gcp/Service/ProductService.java, be/src/main/java/be/domain/search/controller/SearchController.java, be/src/main/java/be/domain/search/controller/VisionController.java, be/src/main/java/be/domain/search/service/VisionService.java
=> GB-90 feat: 이미지 검색 구현

fe/pages/postpairing/index.tsx
=> GB-87 fix: useId 제거

fe/components/inputs/BigInput.tsx, fe/components/modal/CameraModal.tsx, fe/components/pairing/DetailCard.tsx, fe/components/postPairingPage/ImageUpload.tsx, fe/components/wish/WishCard.tsx, fe/pages/allpairing/[id].tsx, fe/pages/beer/[id].tsx, fe/pages/index.tsx, fe/pages/pairing/[id].tsx, fe/pages/postpairing/index.tsx, fe/pages/test.tsx
=> GB-87: fix- 모든 console 주석 제거

be/Dockerfile, be/docker-compose.yml, be/script/deploy.sh, be/script/run.sh, be/src/main/java/be/GetABeerApplication.java, be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/beer/entity/WeeklyBeer.java, be/src/main/java/be/domain/beer/entity/WeeklyBeerCategory.java, be/src/main/java/be/domain/beer/repository/BeerQueryRepository.java, be/src/main/java/be/domain/beer/service/BeerServiceImpl.java, be/src/main/java/be/domain/elasticsearch/controller/EsController.java, be/src/main/java/be/domain/elasticsearch/entity/BeerDocument.java, be/src/main/java/be/domain/elasticsearch/repository/BeerSearchQueryRepository.java, be/src/main/java/be/domain/elasticsearch/service/ElasticsearchService.java, be/src/main/java/be/domain/mail/config/MailConfig.java, be/src/main/java/be/domain/search/repository/SearchQueryRepository.java, be/src/main/java/be/domain/search/service/SearchService.java, be/src/main/java/be/global/config/ElasticsearchConfig.java, be/src/main/java/be/global/config/EmbeddedRedisConfig.java, be/src/main/java/be/global/init/Init.java, be/src/main/resources/Get_A_Beer_Products.csv, be/src/test/java/be/utils/BeerTestConstants.java
- 자잘한 업데이트와 디버깅이 있습니다.
- ES관련 설정을 전부 꺼뒀습니다.
=> GB-90 feat: 맥주 검색 로직 수정

fe/components/WishHeart.tsx, fe/components/beerPage/BeerDetailCard.tsx, fe/components/beerPage/KakaoShareButton.tsx, fe/components/postPairingPage/PostDetailCard.tsx, fe/pages/allpairing/[id].tsx
- 찜 컴포넌트 제작
- 세린님의 페이지 네이션 작업 병합
-------
사실 작업을 하고 싶은데 오늘 서버가 언제 켜질지 몰라서 할 수 있는 작업이 ,, 없을 것 같습니다. 제가 해놓은 것도 그냥 로직만 붙여 놓은 거지 잘 되는지 확인은 못했어요
남은 할일을 한번 더 정리하면,
1. 인기많은 맥주, 비슷한 맥주 데이터 통신 붙여 넣기,,  로그인 되면 추천맥주 통신 붙여넣기
2. 좋아요, 찜,  통신 확인
3. 페어링 post 잘 들어가는 거 확인 되면 페어링 수정 통신 확인
4. 검색 기능 통신(아직 작업을 못하고 있어요)
이번주에 달리려고 했는데 주말엔 코테가 있었고, 수요일은 제가 휴가를 갔고, 목요일부터 안되는게 많아 걱정이네여,, 시간안에 언능 해서 여러분께 폐 끼치고 싶지 않은 마음 뿐입니다,, 늦게 작업 마무리 되는 것 같아 마음이 조급한데, 일단은 오늘은 더 작업을 못할것 같네요,, 월요일에 다시 정상 작동 된다면, 2월에 꼭 제가 맡은 부분은 끝내고 싶은 마음입니다, 밤을 새서라도 해 놓을게요
=> GB-87 feat: 자잘한 작업

fe/atoms/searchingImage.tsx, fe/components/SearchModal.tsx, fe/components/beerPage/BeerDeclare.tsx, fe/components/middleCards/RatingCard.tsx, fe/components/modal/CameraModal.tsx, fe/pages/allrating/[beerid].tsx, fe/pages/editrating/[ratingid].tsx, fe/pages/monthly/index.tsx, fe/pages/mypage/comment.tsx, fe/pages/mypage/rating.tsx, fe/pages/postrating/index.tsx, fe/pages/rating/[ratingid].tsx, fe/pages/search/image.tsx, fe/pages/search/index.tsx, fe/utils/SearchMatcher.tsx
1. 이미지 검색 페이지
2. 페어링으로 검색 기능 추가
=> feat: 이미지 검색 페이지 및 페어링으로 검색 기능 추가

be/src/main/java/be/domain/comment/dto/RatingCommentDto.java, be/src/main/java/be/domain/comment/service/PairingCommentService.java, be/src/main/java/be/domain/comment/service/RatingCommentService.java, be/src/main/java/be/domain/rating/service/RatingService.java
- 평가 삭제 로그인 유저 판별 메서드 주석 해제
- 댓글 등록 닉네임 삭제
- 댓글 삭제 로그인 유저 판별 추가
=> GB-60 fix: 평가 및 댓글 관련 수정

be/.gitignore, be/docker-compose.yml, be/src/main/java/be/domain/beer/dto/BeerDto.java, be/src/main/java/be/domain/beer/entity/MonthlyBeer.java, be/src/main/java/be/domain/beer/mapper/BeerMapper.java, be/src/main/java/be/domain/beertag/entity/BeerTag.java, be/src/main/java/be/global/aop/GetABeerAop.java
=> GB-90 feat: 요구사항 반영

fe/components/SpeechBalloon.tsx, fe/components/beerPage/BeerDetailCard.tsx, fe/components/middleCards/RatingCard.tsx, fe/components/pairing/DetailCard.tsx, fe/components/postPairingPage/PostDetailCard.tsx, fe/pages/mypage/pairing.tsx, fe/pages/pairing/[id].tsx, fe/pages/postpairing/index.tsx
=> GB-87 chore : 자잘한 수정

.github/workflows/gradle.yml
=> GB-96 Deploy : main으로 브랜치 변경

be/src/main/java/be/domain/follow/Follow.java, be/src/main/java/be/domain/follow/FollowController.java, be/src/main/java/be/domain/follow/FollowDto.java, be/src/main/java/be/domain/follow/FollowMapper.java, be/src/main/java/be/domain/follow/FollowQueryRepository.java, be/src/main/java/be/domain/follow/FollowRepository.java, be/src/main/java/be/domain/follow/FollowService.java, be/src/main/java/be/domain/user/dto/UserDto.java, be/src/main/java/be/domain/user/entity/User.java, be/src/main/java/be/domain/user/mapper/UserMapper.java, be/src/main/java/be/global/statistics/repository/BeerStatisticsJdbcRepository.java
=> GB-90 feat: 팔로우 기능 구현

be/src/main/java/be/domain/user/controller/UserPageController.java, be/src/main/java/be/domain/user/dto/UserDto.java, be/src/main/java/be/domain/user/repository/UserQueryRepository.java
=> GB-102 feat: 유저 페이지 완성

fe/components/Alarm.tsx, fe/components/Header.tsx, fe/components/SpeechBalloon.tsx, fe/components/beerPage/PairingTitle.tsx, fe/components/beerPage/RatingTitle.tsx, fe/components/editPairingPage/EditImage.tsx, fe/components/mainPage/BeerCategoryBtn.tsx, fe/components/modal/CameraModal.tsx, fe/components/postPairingPage/ImageUpload.tsx, fe/components/postPairingPage/Loading.tsx, fe/components/smallCards/PopularBeer.tsx, fe/components/smallCards/RecommendBeer.tsx, fe/components/smallCards/SimilarBeer.tsx, fe/components/smallCards/SmallPairingCard.tsx, fe/components/smallCards/SmallRatingCard.tsx, fe/components/wish/WishCard.tsx, fe/next.config.js, fe/package-lock.json, fe/package.json, fe/pages/beer/[id].tsx, fe/pages/editpairing/[id].tsx, fe/pages/index.tsx, fe/pages/mypage/wish.tsx, fe/pages/pairing/[id].tsx, fe/pages/pairingTest.tsx, fe/pages/postpairing/index.tsx, fe/pages/test.tsx, fe/tailwind.config.js, fe/yarn.lock
※※※ npm i heic2any 라이브러리 설치했습니다 ※※※
- 알림 기능 구현
- 이미지 확장자 변환 구현
- 알림 삭제 기능 구현
=> GB-98 feat:알림 기능 및 HEIC이미지 변환 기능 구현

fe/components/SpeechBalloon.tsx, fe/components/button/BackPageBtn.tsx, fe/components/map/MapBrewery.tsx, fe/pages/monthly/index.tsx, fe/pages/mypage/comment.tsx, fe/pages/mypage/rating.tsx, fe/pages/pairing/[id].tsx, fe/pages/rating/[ratingid].tsx, fe/pages/search/image.tsx, fe/pages/search/index.tsx
=> chore: 스타일 통일

fe/components/Chat.tsx, fe/components/NavBar.tsx, fe/components/pairing/PairingCard.tsx, fe/components/share/ShareBtn.tsx, fe/pages/_app.tsx, fe/pages/allpairing/[id].tsx, fe/pages/beer/[id].tsx, fe/pages/editpairing/[id].tsx, fe/pages/index.tsx, fe/pages/mypage/pairing.tsx, fe/pages/mypage/wish.tsx, fe/pages/pairing/[id].tsx
1. 챗 컴포넌트 이동
2. 뒤로가기 수정
3, 이미지 너비 높이 수정
4. 맥주 공유하기 absolute 제거
=> GB-98 chore: 디자인 수정

fe/components/NavBar.tsx, fe/components/smallCards/PopularBeer.tsx, fe/components/smallCards/RecommendBeer.tsx, fe/components/smallCards/SimilarBeer.tsx, fe/pages/beer/[id].tsx, fe/pages/index.tsx
태영님께서 추천맥주 기능 추가해주신거 수정했고
아까 로컬에서는 500 뜨던게 서버에서는 왜 되는지 알아써여 토큰 문제인거 같더라구여
config 로 직접 넣으니 500 은 안떠서 일단은 이렇게 추가해 두려구여!
여기말고 첫 페이지에 사용자 추천 맥주에서도 새로고침시 500 이 떠서 생각보다 헤더에 토큰 담기는 속도가 느린가바여 ,,(?)
근데 또 로컬 아니라 서버에서는 잘 되는게 신기하기도 하고,,
=> GB-98 feat:추천 맥주

be/build.gradle, be/src/main/java/be/domain/follow/FollowService.java, be/src/main/java/be/domain/notice/dto/NotificationDto.java, be/src/main/java/be/domain/notice/entity/Notification.java, be/src/main/java/be/domain/notice/service/NotificationService.java, be/src/main/java/be/domain/user/service/UserService.java, be/src/main/java/be/global/exception/ExceptionCode.java
- 비밀번호 변경 시 전 비밀번호와 동일한 비밀번호 불가하도록 구현
- 팔로우 알림 전송 시 팔로잉 유저 아이디 응답에 포함
- 로그아웃 시 알림 기능으로 인한 user not found 해결
- 디코 에러 모니터링 시간 간격으로 변경 중
=> GB-110 fix: 수정 사항 반영

fe/components/Alarm.tsx, fe/pages/allpairing/[id].tsx, fe/pages/api/axios.ts, fe/pages/beer/[id].tsx, fe/pages/editpairing/[id].tsx, fe/pages/index.tsx, fe/pages/mypage/pairing.tsx, fe/pages/pairing/[id].tsx
=> GB-98 chore: config 추가

be/src/main/java/be/global/aop/GetABeerAop.java, be/src/main/resources/application-dev.yml
=> GB-102 feat: 에러 핸들링, 테스트 코드

fe/components/followPage/FollowBtn.tsx, fe/pages/allpairing/[id].tsx, fe/pages/beer/[id].tsx, fe/pages/follower/[id].tsx, fe/pages/following/[id].tsx, fe/pages/index.tsx, fe/pages/pairing/[id].tsx, fe/pages/pwedit/index.tsx, fe/pages/search/index.tsx, fe/pages/userpage/[id].tsx
밑에 패딩을 안줘서 네브바에 가려 페이지네이션이 안보여 수정했습니다.
=> GB-106 style: 페이지 아래 패딩 수정

fe/components/pairing/DetailCard.tsx, fe/components/postPairingPage/PostDetailCard.tsx, fe/components/smallCards/SmallPairingCard.tsx, fe/components/smallCards/SmallRatingCard.tsx
글자 크기가 조금 작은 거 같아 화면이 커질 때 글씨도 같이 커지도록 조정했슴돠
=> GB-98 chore: 글자 크기 수정

fe/pages/mypage/rating.tsx, fe/pages/pairing/[id].tsx, fe/pages/userpage/[id].tsx
마이 레이팅 페이지 마진 수정
페어링에 맥주 제목 클릭시 맥주페이지 이동 할 수 있게 했습니다.
-> 마이페이지나 유저페이지에서 이동이 가능해야 할 것 같아서
=> GB-106 chore: 마이레이팅 페이지 마진 수정, 페어링 제목 링크이동

fe/components/Alarm.tsx
=> GB-98 chore: 모두 읽음표시 수정

be/build.gradle, be/src/docs/asciidoc/index.adoc, be/src/main/java/be/domain/beer/correction/ErrorCorrectionController.java, be/src/main/java/be/domain/beer/correction/ErrorCorrectionService.java, be/src/main/java/be/domain/beer/entity/Beer.java, be/src/main/java/be/domain/beer/entity/BeerDetailsCounts.java, be/src/main/java/be/domain/beer/entity/BeerDetailsStars.java, be/src/main/java/be/domain/beer/repository/BeerQueryRepository.java, be/src/main/java/be/domain/beer/service/BeerServiceImpl.java, be/src/main/java/be/domain/user/repository/UserRepository.java, be/src/test/java/be/controller/PairingCommentControllerRestDocs.java, be/src/test/java/be/controller/PairingControllerRestDocs.java, be/src/test/java/be/controller/RatingCommentControllerRestDocs.java, be/src/test/java/be/controller/SearchControllerRestDocs.java, be/src/test/java/be/controller/UserPageControllerRestDocs.java
=> GB-102 feat: 테스트 코드

be/src/main/java/be/domain/beercategory/entity/BeerCategory.java, be/src/main/java/be/domain/beertag/entity/BeerTag.java, be/src/main/java/be/global/aop/GetABeerAop.java, be/src/main/java/be/global/security/oauth/service/GoogleService.java, be/src/main/java/be/global/security/oauth/service/KakaoService.java, be/src/main/java/be/global/security/oauth/service/NaverService.java, be/src/main/java/be/global/statistics/analysis/JTableSawController.java, be/src/main/java/be/global/statistics/entity/BeerStatistics.java, be/src/main/java/be/global/statistics/repository/BeerCategoryStatisticsQueryRepository.java, be/src/main/java/be/global/statistics/repository/BeerStatisticsJdbcRepository.java, be/src/main/java/be/global/statistics/repository/BeerStatisticsQueryRepository.java, be/src/main/java/be/global/statistics/repository/BeerTagStatisticsQueryRepository.java, be/src/main/java/be/global/statistics/repository/PairingCategoryStatisticsQueryRepository.java, be/src/test/java/be/controller/OAuthControllerRestDocs.java, be/src/test/java/be/controller/UserPageControllerRestDocs.java
=> GB-102 fix: 로직 수정
